name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: base.svg
          output_action: gist
          commiter_gist: ${{ secrets.METRICS_GIST_ID }}
          config_timezone: Asia/Jakarta
          base: header
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes

      - name: Starred
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: starred.svg
          output_action: gist
          commiter_gist: ${{ secrets.METRICS_GIST_ID }}
          config_timezone: Asia/Jakarta
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
